name: "Setup container"

inputs:
  qemuArch:
    required: true
    description: "The qemu target (e.g linux/arm64). See: https://github.com/tonistiigi/binfmt?tab=readme-ov-file#build-test-image"

  dockerArch:
    required: true
    description: "The docker target (e.g linux/arm64). Can also use SAME_AS_QEMU. See: https://github.com/tonistiigi/binfmt?tab=readme-ov-file#build-test-image"

  image:
    required: true
    description: "The docker image to use"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.qemuArch }}

    - name: Create and run the container
      shell: bash
      run: |
        docker run \
          --detach \
          --interactive \
          --tty \
          --volume $(pwd):/home/container \
          --workdir /home/container \
          --platform ${{ inputs.dockerArch == 'SAME_AS_QEMU' && inputs.qemuArch || inputs.dockerArch }} \
          --name actioncontainer \
          ${{ inputs.image }} /bin/sh
      # We use /bin/sh in combination with --detach and --interactive and --tty to keep the container running.