name: "Upload artifact"

inputs:
  path:
    required: true
    description: "The folder or file you wish to capture."

  name:
    required: true
    description: "The filename (excluding extension)"

  token:
    required: true
    description: "Use secrets.GITHUB_TOKEN"

runs:
  using: "composite"
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: Create archive for release
      if: github.event_name == 'release' && github.event.action == 'created'
      shell: bash
      run: 7z a "${{ inputs.name }}.zip" "${{ github.workspace }}/${{ inputs.path }}" -r

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        repo_token: ${{ inputs.token }}
        file: "${{ inputs.name }}.zip"
        asset_name: "${{ inputs.name }}.zip"
        tag: ${{ github.ref }}