name: "Run in container"

inputs:
  command:
    required: true

  shell:
    required: false
    default: /bin/bash

runs:
  using: "composite"
  steps:
    - name: Run the command
      shell: bash
      run: |
        docker exec \
        --interactive \
        --workdir /home/container \
        actioncontainer ${{ inputs.shell }} <<RIC_EOF
        ${{ inputs.command }}
        RIC_EOF