<?php

declare(strict_types=1);

namespace Serafim\WinUI\Driver\Win32\Lib;

final readonly class SystemMetrics
{
    public const int SM_CXSCREEN = 0;
    public const int SM_CYSCREEN = 1;
    public const int SM_CXVSCROLL = 2;
    public const int SM_CYHSCROLL = 3;
    public const int SM_CYCAPTION = 4;
    public const int SM_CXBORDER = 5;
    public const int SM_CYBORDER = 6;
    public const int SM_CXDLGFRAME = 7;
    public const int SM_CYDLGFRAME = 8;
    public const int SM_CYVTHUMB = 9;
    public const int SM_CXHTHUMB = 10;
    public const int SM_CXICON = 11;
    public const int SM_CYICON = 12;
    public const int SM_CXCURSOR = 13;
    public const int SM_CYCURSOR = 14;
    public const int SM_CYMENU = 15;
    public const int SM_CXFULLSCREEN = 16;
    public const int SM_CYFULLSCREEN = 17;
    public const int SM_CYKANJIWINDOW = 18;
    public const int SM_MOUSEPRESENT = 19;
    public const int SM_CYVSCROLL = 20;
    public const int SM_CXHSCROLL = 21;
    public const int SM_DEBUG = 22;
    public const int SM_SWAPBUTTON = 23;
    public const int SM_RESERVED1 = 24;
    public const int SM_RESERVED2 = 25;
    public const int SM_RESERVED3 = 26;
    public const int SM_RESERVED4 = 27;
    public const int SM_CXMIN = 28;
    public const int SM_CYMIN = 29;
    public const int SM_CXSIZE = 30;
    public const int SM_CYSIZE = 31;
    public const int SM_CXFRAME = 32;
    public const int SM_CYFRAME = 33;
    public const int SM_CXMINTRACK = 34;
    public const int SM_CYMINTRACK = 35;
    public const int SM_CXDOUBLECLK = 36;
    public const int SM_CYDOUBLECLK = 37;
    public const int SM_CXICONSPACING = 38;
    public const int SM_CYICONSPACING = 39;
    public const int SM_MENUDROPALIGNMENT = 40;
    public const int SM_PENWINDOWS = 41;
    public const int SM_DBCSENABLED = 42;
    public const int SM_CMOUSEBUTTONS = 43;
    public const int SM_CXFIXEDFRAME = self::SM_CXDLGFRAME;  /* ;win40 name change */
    public const int SM_CYFIXEDFRAME = self::SM_CYDLGFRAME;  /* ;win40 name change */
    public const int SM_CXSIZEFRAME = self::SM_CXFRAME;  /* ;win40 name change */
    public const int SM_CYSIZEFRAME = self::SM_CYFRAME;  /* ;win40 name change */
    public const int SM_SECURE = 44;
    public const int SM_CXEDGE = 45;
    public const int SM_CYEDGE = 46;
    public const int SM_CXMINSPACING = 47;
    public const int SM_CYMINSPACING = 48;
    public const int SM_CXSMICON = 49;
    public const int SM_CYSMICON = 50;
    public const int SM_CYSMCAPTION = 51;
    public const int SM_CXSMSIZE = 52;
    public const int SM_CYSMSIZE = 53;
    public const int SM_CXMENUSIZE = 54;
    public const int SM_CYMENUSIZE = 55;
    public const int SM_ARRANGE = 56;
    public const int SM_CXMINIMIZED = 57;
    public const int SM_CYMINIMIZED = 58;
    public const int SM_CXMAXTRACK = 59;
    public const int SM_CYMAXTRACK = 60;
    public const int SM_CXMAXIMIZED = 61;
    public const int SM_CYMAXIMIZED = 62;
    public const int SM_NETWORK = 63;
    public const int SM_CLEANBOOT = 67;
    public const int SM_CXDRAG = 68;
    public const int SM_CYDRAG = 69;
    public const int SM_SHOWSOUNDS = 70;
    public const int SM_CXMENUCHECK = 71;
    public const int SM_CYMENUCHECK = 72;
    public const int SM_SLOWMACHINE = 73;
    public const int SM_MIDEASTENABLED = 74;
    public const int SM_MOUSEWHEELPRESENT = 75;
    public const int SM_XVIRTUALSCREEN = 76;
    public const int SM_YVIRTUALSCREEN = 77;
    public const int SM_CXVIRTUALSCREEN = 78;
    public const int SM_CYVIRTUALSCREEN = 79;
    public const int SM_CMONITORS = 80;
    public const int SM_SAMEDISPLAYFORMAT = 81;
    public const int SM_IMMENABLED = 82;
    public const int SM_CXFOCUSBORDER = 83;
    public const int SM_CYFOCUSBORDER = 84;
    public const int SM_TABLETPC = 86;
    public const int SM_MEDIACENTER = 87;
    public const int SM_STARTER = 88;
    public const int SM_SERVERR2 = 89;
    public const int SM_MOUSEHORIZONTALWHEELPRESENT = 91;
    public const int SM_CXPADDEDBORDER = 92;
    public const int SM_DIGITIZER = 94;
    public const int SM_MAXIMUMTOUCHES = 95;
    public const int SM_CMETRICS = 97;
    public const int SM_REMOTESESSION = 0x1000;
    public const int SM_SHUTTINGDOWN = 0x2000;
    public const int SM_REMOTECONTROL = 0x2001;
    public const int SM_CARETBLINKINGENABLED = 0x2002;
    public const int SM_CONVERTIBLESLATEMODE = 0x2003;
    public const int SM_SYSTEMDOCKED = 0x2004;
}
