<?php

declare(strict_types=1);

namespace Local\WebView2;

enum WebErrorStatus: int
{
    case STATUS_UNKNOWN = 0;
    case STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT = 1;
    case STATUS_CERTIFICATE_EXPIRED = 2;
    case STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS = 3;
    case STATUS_CERTIFICATE_REVOKED = 4;
    case STATUS_CERTIFICATE_IS_INVALID = 5;
    case STATUS_SERVER_UNREACHABLE = 6;
    case STATUS_TIMEOUT = 7;
    case STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE = 8;
    case STATUS_CONNECTION_ABORTED = 9;
    case STATUS_CONNECTION_RESET = 10;
    case STATUS_DISCONNECTED = 11;
    case STATUS_CANNOT_CONNECT = 12;
    case STATUS_HOST_NAME_NOT_RESOLVED = 13;
    case STATUS_OPERATION_CANCELED = 14;
    case STATUS_REDIRECT_FAILED = 15;
    case STATUS_UNEXPECTED_ERROR = 16;
}
